import type { Metadata } from "next";
import { Rethink_Sans } from 'next/font/google'

const rethinkSans = Rethink_Sans({
  subsets: ['latin'],
  display: 'swap',
})
import "./globals.css";

export const metadata: Metadata = {
  title: "LearneX",
  description: "Generated by Nishant Gupta",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={rethinkSans.className}
      >
        {children}
      </body>
    </html>
  );
}
